title: awzhak.net

show_excerpts: false # set to true to show excerpts on the homepage

header_pages:

minima:
  date_format: "%b %-d, %Y"
  skin: dark

# Build settings
theme: minima

google_analytics: G-0KNHQC524L

plugins:
 - jekyll-feed
 - jekyll-seo-tag
