baseURL = 'http://awzhak.net/'
title = 'awzhak'
theme = "hugo-coder"
languageCode = 'jp'
defaultcontentlanguage = 'jp'

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsCodefences=true
pygmentsUseClasses=true




[params]
author = "awzhak"
description = "My site"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"
colorScheme = "dark"
hidecolorschemetoggle = false



[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 1
url = "https://twitter.com/awzhak/"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/awzhak/"

[[params.social]]
name = "Annict"
icon = "fa fa-television fa-2x"
weight = 3
url = "https://annict.com/@awzhak/watching"

[[params.social]]
name = "instagram"
icon = "fa fa fa-instagram fa-2x"
weight = 4
url = "https://www.instagram.com/awzhak"

[[params.social]]
name = "EVENTERNOTE"
icon = "fa fa fa-tasks fa-2x"
weight = 4
url = "https://www.eventernote.com/users/awzhak"


# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
